id: I29EE945A
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:03:57.155550
last_modified: 2023-02-09 15:03:57.155662
source_metadata:
  title: 'MSV 1,04: Varṣāvastu'
  language: sa
bases:
  E5A2:
    base_file: E5A2.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
